#include "modding.h"
#include "scene_table.h"

RPCSceneInfo rpcSceneInfo[] = {
    { 0, "Mayor's Residence" },
    { 1, "Majora's Lair" },
    { 2, "Magic Hags' Potion Shop" },
    { 3, "Ranch House & Barn" },
    { 4, "Honey & Darling's Shop" },
    { 5, "Beneath the Graves" },
    { 6, "Southern Swamp (Clear)" },
    { 7, "Curiosity Shop" },
    { 8, "Unknown Scene" },
    { 9, "Unknown Scene" },
    { 10, "Grottos" },
    { 11, "Unknown Scene" },
    { 12, "Unknown Scene" },
    { 13, "Unknown Scene" },
    { 14, "Cutscene Map" },
    { 15, "Unknown Scene" },
    { 16, "Ikana Canyon" },
    { 17, "Pirates' Fortress" },
    { 18, "Milk Bar" },
    { 19, "Stone Tower Temple" },
    { 20, "Treasure Chest Shop" },
    { 21, "Stone Tower Temple (Inverted)" },
    { 22, "Clock Tower Rooftop" },
    { 23, "Before the Portal to Termina" },
    { 24, "Woodfall Temple" },
    { 25, "Path to Mountain Village" },
    { 26, "Ancient Castle of Ikana" },
    { 27, "Deku Scrub Playground" },
    { 28, "Odolwa's Lair" },
    { 29, "Shooting Gallery (Town)" },
    { 30, "Snowhead Temple" },
    { 31, "Milk Road" },
    { 32, "Pirates' Fortress Interior" },
    { 33, "Shooting Gallery (Swamp)" },
    { 34, "Pinnacle Rock" },
    { 35, "Fairy's Fountain" },
    { 36, "Swamp Spider House" },
    { 37, "Oceanside Spider House" },
    { 38, "Astral Observatory" },
    { 39, "The Moon - Deku Trial" },
    { 40, "Deku Palace" },
    { 41, "Mountain Smithy" },
    { 42, "Termina Field" },
    { 43, "Post Office" },
    { 44, "Marine Research Laboratory" },
    { 45, "Damp├⌐'s House" },
    { 46, "Unknown Scene" },
    { 47, "Goron Shrine" },
    { 48, "Zora Hall" },
    { 49, "Trading Post" },
    { 50, "Romani Ranch" },
    { 51, "Twinmold's Lair" },
    { 52, "Great Bay Coast" },
    { 53, "Zora Cape" },
    { 54, "Lottery Shop" },
    { 55, "Unknown Scene" },
    { 56, "Pirates' Fortress Exterior" },
    { 57, "Fisherman's Hut" },
    { 58, "Goron Shop" },
    { 59, "Deku King's Chamber" },
    { 60, "The Moon - Goron Trial" },
    { 61, "Road to Southern Swamp" },
    { 62, "Doggy Racetrack" },
    { 63, "Cucco Shack" },
    { 64, "Ikana Graveyard" },
    { 65, "Goht's Lair" },
    { 66, "Southern Swamp (Poisoned)" },
    { 67, "Woodfall" },
    { 68, "The Moon - Zora Trial" },
    { 69, "Goron Village (Spring)" },
    { 70, "Great Bay Temple" },
    { 71, "Waterfall Rapids" },
    { 72, "Beneath the Well" },
    { 73, "Zora Hall Rooms" },
    { 74, "Goron Village (Winter)" },
    { 75, "Goron Graveyard" },
    { 76, "Sakon's Hideout" },
    { 77, "Mountain Village (Winter)" },
    { 78, "Ghost Hut" },
    { 79, "Deku Shrine" },
    { 80, "Road to Ikana" },
    { 81, "Swordsman's School" },
    { 82, "Music Box House" },
    { 83, "Igos du Ikana's Lair" },
    { 84, "Tourist Information" },
    { 85, "Stone Tower" },
    { 86, "Stone Tower (Inverted)" },
    { 87, "Mountain Village (Spring)" },
    { 88, "Path to Snowhead" },
    { 89, "Snowhead" },
    { 90, "Path to Goron Village (Winter)" },
    { 91, "Path to Goron Village (Spring)" },
    { 92, "Gyorg's Lair" },
    { 93, "Secret Shrine" },
    { 94, "Stock Pot Inn" },
    { 95, "Great Bay Coast (Cutscene)" },
    { 96, "Clock Tower Interior" },
    { 97, "Woods of Mystery" },
    { 98, "Lost Woods" },
    { 99, "The Moon - Link Trial" },
    { 100, "The Moon" },
    { 101, "Bomb Shop" },
    { 102, "Giants' Chamber" },
    { 103, "Gorman Track" },
    { 104, "Goron Racetrack" },
    { 105, "East Clock Town" },
    { 106, "West Clock Town" },
    { 107, "North Clock Town" },
    { 108, "South Clock Town" },
    { 109, "Laundry Pool" },
    { 110, "Unknown Scene" },
    { 111, "Unknown Scene" },
    { 112, "Unknown Scene" },
    { 113, "Unknown Scene" },
    { 114, "Unknown Scene" },
    { 115, "Unknown Scene" },
    { 116, "Unknown Scene" },
    { 117, "Unknown Scene" },
    { 118, "Unknown Scene" },
    { 119, "Unknown Scene" },
    { 120, "Unknown Scene" },
    { 121, "Unknown Scene" },
    { 122, "Unknown Scene" },
    { 123, "Unknown Scene" },
    { 124, "Unknown Scene" },
    { 125, "Unknown Scene" },
    { 126, "Unknown Scene" },
    { 127, "Unknown Scene" },
    { 128, "Unknown Scene" },
    { 129, "Unknown Scene" },
    { 130, "Unknown Scene" },
    { 131, "Unknown Scene" },
    { 132, "Unknown Scene" },
    { 133, "Unknown Scene" },
    { 134, "Unknown Scene" },
    { 135, "Unknown Scene" },
    { 136, "Unknown Scene" },
    { 137, "Unknown Scene" },
    { 138, "Unknown Scene" },
    { 139, "Unknown Scene" },
    { 140, "Unknown Scene" },
    { 141, "Unknown Scene" },
    { 142, "Unknown Scene" },
    { 143, "Unknown Scene" },
    { 144, "Unknown Scene" },
    { 145, "Unknown Scene" },
    { 146, "Unknown Scene" },
    { 147, "Unknown Scene" },
    { 148, "Unknown Scene" },
    { 149, "Unknown Scene" },
    { 150, "Unknown Scene" },
    { 151, "Unknown Scene" },
    { 152, "Unknown Scene" },
    { 153, "Unknown Scene" },
    { 154, "Unknown Scene" },
    { 155, "Unknown Scene" },
    { 156, "Unknown Scene" },
    { 157, "Unknown Scene" },
    { 158, "Unknown Scene" },
    { 159, "Unknown Scene" },
    { 160, "Unknown Scene" },
    { 161, "Unknown Scene" },
    { 162, "Unknown Scene" },
    { 163, "Unknown Scene" },
    { 164, "Unknown Scene" },
    { 165, "Unknown Scene" },
    { 166, "Unknown Scene" },
    { 167, "Unknown Scene" },
    { 168, "Unknown Scene" },
    { 169, "Unknown Scene" },
    { 170, "Unknown Scene" },
    { 171, "Unknown Scene" },
    { 172, "Unknown Scene" },
    { 173, "Unknown Scene" },
    { 174, "Unknown Scene" },
    { 175, "Unknown Scene" },
    { 176, "Unknown Scene" },
    { 177, "Unknown Scene" },
    { 178, "Unknown Scene" },
    { 179, "Unknown Scene" },
    { 180, "Unknown Scene" },
    { 181, "Unknown Scene" },
    { 182, "Unknown Scene" },
    { 183, "Unknown Scene" },
    { 184, "Unknown Scene" },
    { 185, "Unknown Scene" },
    { 186, "Unknown Scene" },
    { 187, "Unknown Scene" },
    { 188, "Unknown Scene" },
    { 189, "Unknown Scene" },
    { 190, "Unknown Scene" },
    { 191, "Unknown Scene" },
    { 192, "Unknown Scene" },
    { 193, "Unknown Scene" },
    { 194, "Unknown Scene" },
    { 195, "Unknown Scene" },
    { 196, "Unknown Scene" },
    { 197, "Unknown Scene" },
    { 198, "Unknown Scene" },
    { 199, "Unknown Scene" },
    { 200, "Unknown Scene" },
    { 201, "Unknown Scene" },
    { 202, "Unknown Scene" },
    { 203, "Unknown Scene" },
    { 204, "Unknown Scene" },
    { 205, "Unknown Scene" },
    { 206, "Unknown Scene" },
    { 207, "Unknown Scene" },
    { 208, "Unknown Scene" },
    { 209, "Unknown Scene" },
    { 210, "Unknown Scene" },
    { 211, "Unknown Scene" },
    { 212, "Unknown Scene" },
    { 213, "Unknown Scene" },
    { 214, "Unknown Scene" },
    { 215, "Unknown Scene" },
    { 216, "Unknown Scene" },
    { 217, "Unknown Scene" },
    { 218, "Unknown Scene" },
    { 219, "Unknown Scene" },
    { 220, "Unknown Scene" },
    { 221, "Unknown Scene" },
    { 222, "Unknown Scene" },
    { 223, "Unknown Scene" },
    { 224, "Unknown Scene" },
    { 225, "Unknown Scene" },
    { 226, "Unknown Scene" },
    { 227, "Unknown Scene" },
    { 228, "Unknown Scene" },
    { 229, "Unknown Scene" },
    { 230, "Unknown Scene" },
    { 231, "Unknown Scene" },
    { 232, "Unknown Scene" },
    { 233, "Unknown Scene" },
    { 234, "Unknown Scene" },
    { 235, "Unknown Scene" },
    { 236, "Unknown Scene" },
    { 237, "Unknown Scene" },
    { 238, "Unknown Scene" },
    { 239, "Unknown Scene" },
    { 240, "Unknown Scene" },
    { 241, "Unknown Scene" },
    { 242, "Unknown Scene" },
    { 243, "Unknown Scene" },
    { 244, "Unknown Scene" },
    { 245, "Unknown Scene" },
    { 246, "Unknown Scene" },
    { 247, "Unknown Scene" },
    { 248, "Unknown Scene" },
    { 249, "Unknown Scene" },
    { 250, "Unknown Scene" },
    { 251, "Unknown Scene" },
    { 252, "Unknown Scene" },
    { 253, "Unknown Scene" },
    { 254, "Unknown Scene" },
    { 255, "Unknown Scene" },

};